import type { Metadata } from "next";
import "./globals.css";
import { HelperProvider } from "@/components/providers/helper-provider";
import { FullLoadingProvider } from "@/components/providers/full-loading-provider";
import { AlertDialogProvider } from "@/components/providers/alert-provider";
import { Kanit } from "next/font/google";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit-sans",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Sunsu email to lark",
  description: "Generated by tk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} antialiased`}>
        <AlertDialogProvider>
          <FullLoadingProvider>
            <HelperProvider>{children}</HelperProvider>
          </FullLoadingProvider>
        </AlertDialogProvider>
      </body>
    </html>
  );
}
