import type { Metadata } from "next";
import "./globals.css";
import { HelperProvider } from "@/components/providers/helper-provider";
import { FullLoadingProvider } from "@/components/providers/full-loading-provider";
import { AlertDialogProvider } from "@/components/providers/alert-provider";
import { Kanit } from "next/font/google";
import { Suspense } from "react";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit-sans",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Email Batch Download",
  description: "Generated by it team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div></div>}>
      <html lang="en">
        <body className={`${kanit.variable} antialiased`}>
          <AlertDialogProvider>
            <FullLoadingProvider>
              <HelperProvider>{children}</HelperProvider>
            </FullLoadingProvider>
          </AlertDialogProvider>
        </body>
      </html>
    </Suspense>
  );
}
